version = 1

[[migrations]]
id = 8554247116241872352
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 6427383451868931045
name = "0001_migration.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 7941505478684009778
name = "0002_migration.sql"
snapshot_name = "0002_snapshot.toml"
