version = 1

[schema]

[[schema.tables]]
id = 0
name = "rate_limit_buckets"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "bucket_key"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "action"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "bucket_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "tokens"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "last_refill"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_rate_limit_buckets_by_bucket_key"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 1
name = "api_tokens"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 4 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "user_id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "token"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 5 }
name = "last_used_at"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 6 }
name = "revoked"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 1, index = 7 }
name = "resource_scopes"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 8 }
name = "action_scopes"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 9 }
name = "expired_at"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_api_tokens_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 2
name = "posts"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 4 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "user_id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "title"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "content"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "published"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 2, index = 5 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 6 }
name = "updated_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_posts_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 3
name = "users"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 4 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "gh_id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "gh_login"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 3 }
name = "name"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 4 }
name = "email"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 5 }
name = "gh_avatar"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 6 }
name = "is_active"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 3, index = 7 }
name = "account_lock_reason"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 8 }
name = "account_lock_until"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 9 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 10 }
name = "updated_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_users_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 3, index = 1 }
name = "index_users_by_gh_id"
on = 3
columns = [{ column = { table = 3, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true
